--- a/.github/workflows/build-core-pipes.yml
+++ b/.github/workflows/build-core-pipes.yml
@@ -3,7 +3,7 @@
 on:
   push:
     paths:
-      - 'pipes/**' # or this workflow change
+      - 'pipes/**'
       - 'build-core-pipes.yml'
     branches:
       - main
@@ -46,6 +46,4 @@
           done
           
           echo "listing all zip files:"
-          ls -la *.zip || echo "no zip files found"
-
-   +          ls -la *.zip || echo "no zip files found"